<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Errores</title>
  </head>
  <body>
    <script>
      //   ///CALLBACKS
      //   function sumarNumeros(a, b, callback) {
      //     setTimeout(() => {
      //       if (typeof a != "number" || typeof b != "number") {
      //         return callback(new Error("Algún argumento no es número"));
      //       }
      //       callback(a + b, null);
      //     }, 1000);
      //   }
      //   sumarNumeros(1, 2, function (resolve, reject) {
      //     if (reject) {
      //       console.log(reject);
      //     } else {
      //       console.log(resolve);
      //     }
      //   });

      ///PROMESAS
      //   function sumarNumeros(a, b) {
      //     return new Promise(function (resolve, reject) {
      //       setTimeout(() => {
      //         if (typeof a != "number" || typeof b != "number") {
      //             reject( new Error('Ambos argumentos deben de ser número'))
      //         }else{
      //             resolve(a+b)
      //         }
      //       }, 1000);
      //     });
      //   }

      //   sumarNumeros(1, 2)
      //   .then((respuesta)=>{
      //     console.log(respuesta)
      //   })
      //   .catch((error)=>{
      //     console.log(error)
      //   })

      ///ASYNC AWAIT
      function sumarNumeros(a, b) {
        if (typeof a != "number" || typeof b != "number") {
          throw new Error("Ambos argumentos deben de ser número");
        }
        return a + b;
      }

      async function manejarErrores() {
        try {
          let resultado = await sumarNumeros('2', 3);
          console.log(resultado);
        } catch (error) {
          console.error(error.message);
        }
      }
      manejarErrores();
    </script>
  </body>
</html>
